# These are supported funding model platforms

github: [YadgahOrg] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: YadgahPatreon # Replace with a single Patreon username
open_collective: YadgahCollective # Replace with a single Open Collective username
community_bridge: yadgah-project # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: YadgahLiberapay # Replace with a single Liberapay username
issuehunt: YadgahIssuehunt # Replace with a single IssueHunt username
custom: ['http://www.coffeete.ir/dadmehr'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
